// Adapted from public osTRIS 0.3, Apache-2.0; see NOTICE.
package org.stir.config;
import es.idynamicsax.idax.tenant.*; import es.idynamicsax.idax.repository.auth.AuthLocalIdentityLookupRepository; import es.idynamicsax.idax.service.auth.LocalIdentitySubjectPolicy; import org.stir.security.StirJwtAuthFilter; import jakarta.servlet.DispatcherType; import org.springframework.context.annotation.*; import org.springframework.http.*; import org.springframework.security.config.Customizer; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.web.SecurityFilterChain; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;
@Configuration @EnableWebSecurity public class StirSecurityConfig {
 // Public instance branding (site name/base URL/support/locales) has to be readable before login -
 // it carries no tenant or user data, so it is safe to expose unauthenticated (see InstanceController).
 @Bean SecurityFilterChain chain(HttpSecurity h,StirJwtAuthFilter jwt,TenantContextFilter tenant)throws Exception{return h.cors(Customizer.withDefaults()).csrf(x->x.disable()).httpBasic(x->x.disable()).formLogin(x->x.disable()).sessionManagement(x->x.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
  .headers(head->head.contentSecurityPolicy(csp->csp.policyDirectives("default-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self'; frame-ancestors 'none'; base-uri 'self'"))
   .frameOptions(frame->frame.deny()).referrerPolicy(ref->ref.policy(org.springframework.security.web.header.writers.ReferrerPolicyHeaderWriter.ReferrerPolicy.STRICT_ORIGIN_WHEN_CROSS_ORIGIN)))
  .exceptionHandling(x->x.authenticationEntryPoint((req,res,e)->res.sendError(HttpStatus.UNAUTHORIZED.value()))).authorizeHttpRequests(a->a.dispatcherTypeMatchers(DispatcherType.ASYNC,DispatcherType.ERROR).permitAll().requestMatchers(HttpMethod.OPTIONS,"/**").permitAll().requestMatchers("/actuator/health/**","/actuator/info","/swagger-ui/**","/v3/api-docs/**","/api/stir/instance").permitAll().anyRequest().authenticated()).addFilterBefore(jwt,UsernamePasswordAuthenticationFilter.class).addFilterAfter(tenant,StirJwtAuthFilter.class).build();}
 @Bean TenantContextFilter tenantContextFilter(TenantResolver r,AppUserResolver u,AuthLocalIdentityLookupRepository identities,LocalIdentitySubjectPolicy subjects){return new TenantContextFilter(r,u,identities,subjects);}
}
